
SOURCE_DEM_PATH=/media/sf_D_DRIVE/data/dem/srtm1arc_pottenstein_2014
SOURCE_DEM_PREFIX=n49_e011_1arc_v3
SOURCE_DEM_EXT=tif

SOURCE_BOUND_PATH=/media/sf_D_DRIVE/data/adm/osm_pottenstein_2017
SOURCE_BOUND_PREFIX=osm_2017_pottenstein_32632
SOURCE_BOUND_EXT=shp

SOURCE_ORTHO_PATH=/media/sf_D_DRIVE/data/ortho/pottenstein_sentinel2__L1C_T32UPA_A010644_20170706T102301/orig/S2A_MSIL1C_20170706T102021_N0205_R065_T32UPA_20170706T102301.SAFE/GRANULE/L1C_T32UPA_A010644_20170706T102301/IMG_DATA
SOURCE_ORTHO_RED_PREFIX=T32UPA_20170706T102021_B04
SOURCE_ORTHO_RED_VALMIN=150
SOURCE_ORTHO_RED_VALMAX=2000
SOURCE_ORTHO_GREEN_PREFIX=T32UPA_20170706T102021_B03
SOURCE_ORTHO_GREEN_VALMIN=150
SOURCE_ORTHO_GREEN_VALMAX=2000
SOURCE_ORTHO_BLUE_PREFIX=T32UPA_20170706T102021_B02
SOURCE_ORTHO_BLUE_VALMIN=150
SOURCE_ORTHO_BLUE_VALMAX=2000
SOURCE_ORTHO_EXT=jp2



TARGET_DEM_PATH=./demodata_highres
TARGET_DEM_PREFIX=pottenstein_srtm1arc_2014_proj_res_clip

TARGET_BOUND_PATH=./demodata_highres
TARGET_BOUND_PREFIX=__pottenstein_osm_2017_proj_clip
TARGET_BOUNDRAST_PATH=./demodata_highres
TARGET_BOUNDRAST_PREFIX=pottenstein_osm_2017_proj_clip_rast

TARGET_ORTHO_PATH=./demodata_highres
TARGET_ORTHO_RED_PREFIX=__pottenstein_s2_2017_red_val
TARGET_ORTHO_GREEN_PREFIX=__pottenstein_s2_2017_green_val
TARGET_ORTHO_BLUE_PREFIX=__pottenstein_s2_2017_blue_val
TARGET_ORTHOMERGE_PREFIX=__pottenstein_s2_2017_val_merge
TARGET_ORTHOWARP_PREFIX=pottenstein_s2_2017_val_merge_proj_res_clip
TARGET_ORTHO_VALMIN=0
TARGET_ORTHO_VALMAX=255

TARGET_XMIN=668974
TARGET_YMIN=5508034
TARGET_XMAX=679249
TARGET_YMAX=5523350

TARGET_EPSG=32632
TARGET_XRES=10
TARGET_YRES=10




## DEM
rm "$TARGET_DEM_PATH"/"$TARGET_DEM_PREFIX".tif
gdalwarp -t_srs "EPSG:$TARGET_EPSG" -te "$TARGET_XMIN" "$TARGET_YMIN" "$TARGET_XMAX" "$TARGET_YMAX" -tr "$TARGET_XRES" "$TARGET_YRES" -overwrite "$SOURCE_DEM_PATH"/"$SOURCE_DEM_PREFIX"."$SOURCE_DEM_EXT" "$TARGET_DEM_PATH"/"$TARGET_DEM_PREFIX".tif


## BOUNDARIES
rm "$TARGET_BOUND_PATH"/"$TARGET_BOUND_PREFIX".*
rm "$TARGET_BOUNDRAST_PATH"/"$TARGET_BOUNDRAST_PREFIX".*
ogr2ogr -f "ESRI Shapefile" -t_srs "EPSG:$TARGET_EPSG" -clipsrc "$TARGET_XMIN" "$TARGET_YMIN" "$TARGET_XMAX" "$TARGET_YMAX" -skipfailures -overwrite "$TARGET_BOUND_PATH"/"$TARGET_BOUND_PREFIX".shp "$SOURCE_BOUND_PATH"/"$SOURCE_BOUND_PREFIX"."$SOURCE_BOUND_EXT"
gdal_rasterize -burn 1 -te "$TARGET_XMIN" "$TARGET_YMIN" "$TARGET_XMAX" "$TARGET_YMAX" -tr "$TARGET_XRES" "$TARGET_YRES" "$SOURCE_BOUND_PATH"/"$SOURCE_BOUND_PREFIX".shp "$TARGET_BOUNDRAST_PATH"/"$TARGET_BOUNDRAST_PREFIX".tif


## ORTHO
rm "$TARGET_ORTHO_RED_PATH"/"$TARGET_ORTHO_RED_PREFIX".tif
rm "$TARGET_ORTHO_GREEN_PATH"/"$TARGET_ORTHO_GREEN_PREFIX".tif
rm "$TARGET_ORTHO_BLUE_PATH"/"$TARGET_ORTHO_BLUE_PREFIX".tif
rm "$TARGET_ORTHO_PATH"/"$TARGET_ORTHOMERGE_PREFIX".tif
rm "$TARGET_ORTHO_PATH"/"$TARGET_ORTHOWARP_PREFIX".tif 

gdal_translate -of GTiff -ot Byte -scale "$SOURCE_ORTHO_RED_VALMIN" "$SOURCE_ORTHO_RED_VALMAX" "$TARGET_ORTHO_VALMIN" "$TARGET_ORTHO_VALMAX" "$SOURCE_ORTHO_PATH"/"$SOURCE_ORTHO_RED_PREFIX"."$SOURCE_ORTHO_EXT" "$TARGET_ORTHO_PATH"/"$TARGET_ORTHO_RED_PREFIX".tif
gdal_translate -of GTiff -ot Byte -scale "$SOURCE_ORTHO_GREEN_VALMIN" "$SOURCE_ORTHO_GREEN_VALMAX" "$TARGET_ORTHO_VALMIN" "$TARGET_ORTHO_VALMAX" "$SOURCE_ORTHO_PATH"/"$SOURCE_ORTHO_GREEN_PREFIX"."$SOURCE_ORTHO_EXT" "$TARGET_ORTHO_PATH"/"$TARGET_ORTHO_GREEN_PREFIX".tif
gdal_translate -of GTiff -ot Byte -scale "$SOURCE_ORTHO_BLUE_VALMIN" "$SOURCE_ORTHO_BLUE_VALMAX" "$TARGET_ORTHO_VALMIN" "$TARGET_ORTHO_VALMAX" "$SOURCE_ORTHO_PATH"/"$SOURCE_ORTHO_BLUE_PREFIX"."$SOURCE_ORTHO_EXT" "$TARGET_ORTHO_PATH"/"$TARGET_ORTHO_BLUE_PREFIX".tif

gdal_merge.py -separate -of GTiff -o "$TARGET_ORTHO_PATH"/"$TARGET_ORTHOMERGE_PREFIX".tif "$TARGET_ORTHO_PATH"/"$TARGET_ORTHO_RED_PREFIX".tif "$TARGET_ORTHO_PATH"/"$TARGET_ORTHO_GREEN_PREFIX".tif "$TARGET_ORTHO_PATH"/"$TARGET_ORTHO_BLUE_PREFIX".tif
gdalwarp -t_srs "EPSG:$TARGET_EPSG" -overwrite -te "$TARGET_XMIN" "$TARGET_YMIN" "$TARGET_XMAX" "$TARGET_YMAX" -tr "$TARGET_XRES" "$TARGET_YRES" "$TARGET_ORTHO_PATH"/"$TARGET_ORTHOMERGE_PREFIX".tif "$TARGET_ORTHO_PATH"/"$TARGET_ORTHOWARP_PREFIX".tif 

